name: Performance Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  perf-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install
      - name: Get Vercel Preview URL
        id: get_preview
        run: |
          PREVIEW_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            "https://api.vercel.com/v6/deployments?projectId=${{ secrets.VERCEL_PROJECT_ID }}&target=preview" \
            | jq -r '.deployments[0].url')
          echo "TARGET_URL=https://$PREVIEW_URL" >> $GITHUB_ENV

      - name: Run Lighthouse
        run: npm run run-lighthouse

      - name: Compare & Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: npm run compare-comment
